# Default configuration for run_pipeline.py

workspace: /media/arialamar/
seq_name: 5cp

estimate_to_colmap:
  vrs: recordings/${seq_name}.vrs
  estimate: est/${seq_name}.txt
  mps_folder: mps/mps_${seq_name}_vrs/ # necessary if use_mps is true
  images: image_stream
  colmap_model: initial_recon

sensor:
  camera_model: RAD_TAN_THIN_PRISM_FISHEYE

keyframing:
  keyframes: keyframes
  kf_model: keyframe_recon
  
  max_rotation: 20.0
  max_distance: 1.0
  max_elapsed: 1e9 # 1 second in ns

triangulation:
  hloc: hloc
  pairs_file: pairs.txt
  tri_model: triangulated_recon

  feature_conf: aliked-n16
  matcher_conf: aliked+lightglue
  retrieval_conf: netvlad
  num_retrieval_matches: 5

  # relaxed triangulation
  # https://github.com/colmap/colmap/blob/dbdb3cd5a9a90a01b7e1096905ba2ffc34a68b82/src/colmap/sfm/incremental_triangulator.h
  merge_max_reproj_error: 4.0
  complete_max_reproj_error: 4.0
  min_angle: 1.5
  
  # https://github.com/colmap/colmap/blob/dbdb3cd5a9a90a01b7e1096905ba2ffc34a68b82/src/colmap/sfm/incremental_mapper.h
  filter_max_reproj_error: 4.0
  filter_min_tri_angle: 1.5

optimization:
  general:
    optim_model: optim_recon
    use_callback: true
    max_num_iterations: 10
    normalize_reconstruction: false
  
  cam:
    feature_std: 1.0
    optimize_cam_intrinsics: false
    optimize_cam_from_rig: false
  
  imu:
    optimize_scale: false
    optimize_gravity: false
    optimize_imu_from_rig: false
    optimize_bias: false
    gyro_infl: 20.0
    acc_infl: 1.0
    integration_noise_density: 0.05

mps:
  use_mps: false
  use_online_calibration: false # relevant only when use_mps is true (for online calib file)
  has_slam_drops: false
