import argparse
from pathlib import Path

import pycolmap

from lamaria import logger
from lamaria.eval.pgt_evaluation import evaluate_wrt_pgt
from lamaria.structs.sparse_eval import SparseEvalResult
from lamaria.structs.trajectory import Trajectory
from lamaria.utils.metrics import calculate_pose_recall


def run(
    estimate: Path,
    gt_estimate: Path,
    sparse_eval_result: Path,
) -> bool:
    """Evaluate an estimated trajectory with respect to a pseudo
    ground-truth trajectory that observes control points.

    Args:
        estimate (Path): Path to the pose estimate file.
        gt_estimate (Path): Path to the pGT pose estimate file.
        sparse_eval_result (Path): Path to the .npy file containing
            SparseEvalResult data. This file is generated by
            `evaluate_wrt_control_points`, and is needed to
            transform the estimated trajectory to the pGT.
    Returns:
        bool: True if the evaluation was successful, False otherwise.
    """

    est_traj = Trajectory.load_from_file(estimate, invert_poses=False)
    if not est_traj.is_loaded():
        logger.error("Estimate could not be loaded")
        return False

    gt_traj = Trajectory.load_from_file(gt_estimate, invert_poses=False)
    if not gt_traj.is_loaded():
        logger.error("pGT Estimate could not be loaded")
        return False

    result = SparseEvalResult.load_from_npy(sparse_eval_result)
    if result is None:
        logger.error("SparseEvalResult could not be loaded")
        return False

    sim3d = result.alignment
    if not isinstance(sim3d, pycolmap.Sim3d):
        logger.error("No valid Sim3d found in SparseEvalResult")
        return False

    error = evaluate_wrt_pgt(est_traj, gt_traj, sim3d)

    if error is None:
        logger.error("pGT evaluation failed.")
        return False

    for threshold in [1.0, 5.0]:
        pose_recall = calculate_pose_recall(error, len(gt_traj), threshold)
        logger.info(f"Pose Recall @ {threshold}m: {pose_recall:.4f}")

    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Evaluate an estimated trajectory with respect to pGT."
        " Requires a SparseEvalResult .npy file."
    )
    parser.add_argument(
        "--estimate",
        type=Path,
        required=True,
        help="Path to the pose estimate file.",
    )
    parser.add_argument(
        "--gt_estimate",
        type=Path,
        required=True,
        help="Path to the pGT pose estimate file.",
    )
    parser.add_argument(
        "--sparse_eval_result",
        type=Path,
        required=True,
        help="Path to the .npy file containing SparseEvalResult data."
        "Result of `evaluate_wrt_control_points`.",
    )
    args = parser.parse_args()
    _ = run(
        args.estimate,
        args.gt_estimate,
        args.sparse_eval_result,
    )
