run:
  seq_id: 5cp
  vrs_file: ${run.seq_id}.vrs

flags:
  use_mps: false
  use_device_calibration: true # relevant only when use_mps is true (for online calib file)

paths:
  base: /media/arialamar/
  recordings: ${paths.base}/recordings/ # always needed
  estimates: ${paths.base}/estimates/ # estimates in seq_id.txt format
  
  mps: ${paths.base}/mps/ # not necessary if use_mps is false

  output:
    base: ${paths.base}/test/
    images: image_stream/
  
    keyframes: keyframes/
    init_model: empty_recon/
    kf_model: keyframe_recon/
    tri_model: triangulated_recon/
    optim_model: optim_recon/

    full_ts: timestamps/full.npy
    kf_ts: timestamps/keyframe.npy

    rect_imu_file: rect_imu.npy

camera:
  model: RAD_TAN_THIN_PRISM_FISHEYE

vrs_streams:
  left_cam_stream_id: 1201-1
  right_cam_stream_id: 1201-2
  imu_right_stream_id: 1202-1

keyframing:
  max_rotation: 20.0
  max_distance: 1.0
  max_elapsed: 1.0

triangulation:
  pairs_file: pairs.txt
  feature_conf: aliked-n16
  matcher_conf: aliked+lightglue
  retrieval_conf: netvlad

optimization:
  feature_std: 1.0
  use_callback: true
  max_num_iterations: 10
  normalize_reconstruction: false
  optimize_cam_intrinsics: false
  optimize_cam_from_rig: false
  optimize_scale: false
  optimize_gravity: false
  optimize_imu_from_rig: false
  optimize_bias: false
  gyro_infl: 20.0
  acc_infl: 1.0
  integration_noise_density: 0.05
  keep_imu_residuals: true
