name: Format and Lint Checks

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  check:
    name: Format and Lint Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check code format
        run: |
          set +x -euo pipefail
          python -m pip install ruff==0.15.20
          ./format.sh --all
          git diff --name-only
          git diff --exit-code || (echo "Code formatting failed" && exit 1)
