name: Format and Lint Checks
on:
  push:
    branches:
      - main
    paths:
      - '*.py'
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
jobs:
  check:
    name: Format and Lint Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Check code format
        run:  |
          python -m pip install --upgrade pip
          python -m pip install ruff==0.12.7
          bash ./format.sh
          git diff --name-only
          git diff --exit-code || (echo "Code formatting failed" && exit 1)
